server:
  port: 8080
spring:
  application:
    name: application-gateway

  # Настройка OAuth2 клиента
  security:
    oauth2:
      client:
        provider:
          keycloak:
            token-uri: http://localhost:8090/realms/demo/protocol/openid-connect/token
        registration:
          gateway-client:
            provider: keycloak
            client-id: gateway_client_id
            client-secret: wLyISkSJxaQhyjO5fO3APxY2ZXhTiUwT
            scope: resource.read
            authorization-grant-type: client_credentials

  # Настройка маршрутизации Gateway
  cloud:
    gateway:
      routes:
        - id: to-service-exchange # ID роута
          uri: http://localhost:8082  # URI микросервиса, на который следует перенаправлять запрос
          predicates:
            - Path=/api/hello # URI поступающего в гейтвей запроса, которому матчится роут
          filters:
            - TokenRelay=gateway-client