services:
  keycloak-service:
    container_name: keycloak-service
    image: quay.io/keycloak/keycloak:26.1.3
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command:
      - start-dev
    ports:
      - "8090:8080"
    networks:
      - back
    restart: unless-stopped

  exchange-db:
    image: postgres:16
    container_name: exchange-db
    environment:
      POSTGRES_DB: ${EXCHANGE_DB_NAME} # имя базы, которая создаётся при старте контейнера
      POSTGRES_USER: ${EXCHANGE_DB_USERNAME}
      POSTGRES_PASSWORD: ${EXCHANGE_DB_PASSWORD}
    ports:
      - "5435:5432"
    networks:
      - back

networks:
  back:
    driver: bridge